export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTER_INFO = 'FETCH_POSTER_INFO';
export const POST_COMMENT_POST = 'POST_COMMENT_POST';
export const FETCH_FREINDS_LIST = 'FETCH_FREINDS_LIST';
export const FETCH_PROFILE = 'FETCH_PROFILE';